# Import des bibliothèques et chargement des données

In [98]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import AdaBoostClassifier
import pandas as pd
import numpy as np

In [105]:
data = pd.read_csv("spambase.data").values
np.random.shuffle(data) #Cela donne une table numpy contenant des valeurs numériques

# Préparation des données

In [106]:
#Essai numéro 1
#X = [i[:-1] for i in data]
#print(X)

#Essai numéro 2
X = np.zeros(shape = (4600,57)) #print(data.shape)
for i in range(len(data)):
    X [i] = data[i][:-1]
print(X)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 1.0533e+01 6.5000e+01 1.5800e+02]
 [1.1700e+00 3.5200e+00 0.0000e+00 ... 1.0000e+00 1.0000e+00 1.4000e+01]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 1.4000e+00 3.0000e+00 7.0000e+00]
 ...
 [1.5000e-01 0.0000e+00 1.2200e+00 ... 5.1010e+00 6.3000e+01 8.0100e+02]
 [0.0000e+00 0.0000e+00 8.5000e-01 ... 1.2060e+00 7.0000e+00 1.1700e+02]
 [0.0000e+00 0.0000e+00 1.5000e-01 ... 5.4230e+00 5.1000e+01 1.1280e+03]]


In [127]:
Y = np.zeros(shape = (4600,1)) #print(data.shape)
for i in range(len(data)):
    Y[i] = data[i][-1]
Y = Y.ravel()
print(Y)

[1. 0. 0. ... 1. 1. 1.]


In [128]:
Xtrain = X[:-100]
Ytrain = Y[:-100]

In [129]:
Xtest = X[-100:]
Ytest = Y[-100:]

# Chargement des modèles

In [132]:
modelMulti = MultinomialNB()
modelMulti.fit(Xtrain, Ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [133]:
precisionMulti = modelMulti.score(Xtest, Ytest)
print("Précision pour NB:", precisionMulti) # Résultat de 78% de précision

Précision pour NB: 0.78


In [134]:
#Cette fois-ci avec AdaBoostClassifier
modelAda = AdaBoostClassifier()
modelAda.fit(Xtrain, Ytrain)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [135]:
precisionAda = modelAda.score(Xtest, Ytest)
print("Précision pour NB:", precisionAda) # Résultat de 92% de précision

Précision pour NB: 0.92
