In [40]:
import random
classes = ["A", "B", "C", "D"]
y_test = []
for i in range(25):
    pos = random.randint(0, len(classes)-1)
    y_test.append(classes[pos])
print(y_test)

['A', 'D', 'B', 'B', 'D', 'D', 'B', 'B', 'B', 'B', 'A', 'D', 'B', 'B', 'B', 'C', 'A', 'C', 'A', 'C', 'D', 'B', 'D', 'C', 'C']


In [2]:
clust = [[],[],[],[]]
y_pred = []
for i in range(25):
    num_clust = random.randint(0, len(clust)-1)
    clust[num_clust].append(i)
    y_pred.append(num_clust)
print(clust)
print(y_pred)

[[10, 15, 17, 21], [0, 4, 5, 11, 12, 14, 16, 23], [1, 6, 7, 9, 24], [2, 3, 8, 13, 18, 19, 20, 22]]
[1, 2, 3, 3, 1, 1, 2, 2, 3, 2, 0, 1, 1, 3, 1, 0, 1, 0, 3, 3, 3, 0, 3, 1, 2]


In [50]:
def associer_cluster_classes(y_pred, y_test):
  import numpy
  from sklearn.metrics.cluster import contingency_matrix
  matrice1 = contingency_matrix(y_pred, y_test)
  matrice =  [numpy.ndarray.tolist(l) for l in matrice1]
  dic_clusters = {}
  while len(dic_clusters)<len(matrice):
    for cpt, ligne in enumerate(matrice):
      m = max(ligne)
      nb = ligne.count(m)
      if m == numpy.amax(matrice):
        pos = ligne.index(m)
        if cpt not in dic_clusters:
          dic_clusters[cpt] = pos
          matrice[cpt] = [0, 0, 0, 0]
          for i in range(len(matrice)):
            matrice[i][pos]=0
  return dic_clusters, matrice1

In [51]:
def evaluer_clustering(nom_classes, y_pred, y_test):
  dic_classes = {classe:cpt for cpt, classe in enumerate(nom_classes)}
  y_test = [dic_classes[x] for x in y_test]
  dic_clusters, matrice= associer_cluster_classes(y_pred, y_test)
  print(matrice)
  dic= {}
  for num_cluster, ligne in enumerate(matrice):
    num_classe = dic_clusters[num_cluster]
    VP = ligne[num_classe]
    FP = sum(ligne)-VP
    L =[ x[num_classe] for x in matrice]
    FN = sum(L)-VP
    if VP!=0:
      R = VP/(VP+FN)
      P = VP/(VP+FP)
      beta = 1
      F = (1+beta*beta)*(P*R)/((beta*beta*P)+R)
    else:
      R, P, F =0, 0, 0
    resultats = {"Rappel":round(R, 4), "Précision":round(P, 4), "F-mesure":round(F,4)}
    dic[nom_classes[num_classe]] = resultats
  return dic

classes = ["A", "B", "C", "D"]
## la liste des noms de classes
y_test = ['A', 'D', 'B', 'B', 'D', 'D', 'B', 'B', 'B', 'B', 'A',
          'D', 'B', 'B', 'B', 'C', 'A', 'C', 'A', 'C', 'D', 'B', 'D', 'C', 'C']
##y_test la liste des étiquettes de chaque document
y_pred =[1, 2, 3, 3, 1, 1, 2, 2, 3, 2, 0, 1, 1, 3, 1, 0, 1, 0, 3, 3, 3, 0, 3, 1, 2]
##y_pred : la liste des clusters de chaque document
d = evaluer_clustering(classes, y_pred, y_test)
## dé donne pour chaque classe l'évaluation
print(d)

[[1 1 2 0]
 [2 2 1 3]
 [0 3 1 1]
 [1 4 1 2]]
{'C': {'Rappel': 0.4, 'Précision': 0.5, 'F-mesure': 0.4444}, 'D': {'Rappel': 0.5, 'Précision': 0.375, 'F-mesure': 0.4286}, 'A': {'Rappel': 0, 'Précision': 0, 'F-mesure': 0}, 'B': {'Rappel': 0.4, 'Précision': 0.5, 'F-mesure': 0.4444}}
